install: ant
jdk: 
  - oraclejdk8
language: java
notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients: 
      - brendahaberkonb@gmail.com
      - sabrinajodara@gmail.com
      - nicolasbisso7@gmail.com
      - matiasarielfigueroa@gmail.com
script: "ant integracion-continua"
